### ISSUE TITLE
[Information] using "successful" cpmtools with a recreated 128MB RC2040 .cf

### ISSUE THREAD

**Issue by guidol70** [ExtremeElectronics/RC2040#5]
// CPM_RC2040.cf     = https://github.com/ExtremeElectronics/RC2040/raw/main/SD%20Card%20Contents/CPMIncTransient.zip
// CPM128MB_org.img  = https://github.com/RC2014Z80/RC2014/raw/master/CPM/CPM%20128MB%20inc%20transient%20apps.zip

// Google Groups thread about the comtools diskdef for .img files
// search for rc2014cf-cpmtools-diskdefs.txt
// from <irjustman@gmail.com> 18.05.2017, 13:46:14 through RC2014-Z80

// Info from ```
https://github.com/EtchedPixels/RC2014/blob/master/OUTDATED_INSTRUCTIONS.md
// In other words the IDE disk format (.cf) has (additionally to the .img )
// a 1K header that holds meta-data and the virtual identify block.

// Extrating the 1K header from the original 512MB CPM_RC2040.cf
dd if=./CPM_RC2040.cf bs=512 count=2 of=./CF1k_Header.bin

// Creating a working copy of the CPM128MB_org.img
cp ./CPM128MB_org.img ./CPM128MB.img

// copying Worstar to Drive O: on the working copy 
cpmcp -f rc2014o ./CPM128MB.img /toshiba/wordstar/*.* 0:

// copying some software to Drive A: on the working copy 
cpmcp -f rc2014a ./CPM128MB.img ../RUNCPM/*.* 0:

//checking copied files on drive a in the working copy
cpmls -f rc2014a ./CPM128MB.img

// creating NEW CPMIncTransient.cf out of the 1K header and 128MB working copy
// creating with > a NEW CPMIncTransient.cf with the content of the 1K header
dd if=./CF1k_Header.bin > ./CPMIncTransient.cf

// appending the 128MB working copy with >> to the a NEW CPMIncTransient.cf
dd if=./CPM128MB.img >> ./CPMIncTransient.cf
``

[Using_cpmtools_with_cf_image.txt](https://github.com/ExtremeElectronics/RC2040/files/8442540/Using_cpmtools_with_cf_image.txt)
[rc2014cf-cpmtools-diskdefs.zip](https://github.com/ExtremeElectronics/RC2040/files/8442538/rc2014cf-cpmtools-diskdefs.zip)
[CPMIncTransient_128MB.zip](https://github.com/ExtremeElectronics/RC2040/files/8442539/CPMIncTransient_128MB.zip)
`

**Comment by guidol70** [comment]
Another "success" ;)
I did rethink the diskdef from the google-groups thread and came to the conclusion that for adding the 1K (1024 bytes) header to an partition offset for cpmtools we have to go from an offset in Tracks to an offset in Sectors - because 1 Sector is 512 bytes big and 2 Sectors are equal to our 1K header :)
So I created a little formular which calculates the offset from partition to partition in sectors including the 2 sectors we add for the header.

Calculation-description is - as comment - at the top of the diskdef-file ;)

Drive are named from A: (rc2040a) to P: (rc2040p)
(formerly rc2014a to rc2014p)

A command is like
cpmls -f rc2040a ./CPMIncTransient.cf
or
cpmcp -f rc2040a ./CPMIncTransient.cf /toshiba/MBASIC.COM 0:

And it did work without the fiddling with dd and the 1K header :)
on the - in the CPMIncTransient_128MB.zip - included .cf

[rc2040cf-cpmtools-diskdefs.zip](https://github.com/ExtremeElectronics/RC2040/files/8454934/rc2040cf-cpmtools-diskdefs.zip)

**Comment by ExtremeElectronics** [comment]
This will only work with a 128MB .cf image (see above) - 
But I anyone of you are also using Windows:
Today I did find the CP/M Disk Manager for 64/128MB .cf/.dsk images at https://t.co/gLkii8Uljo

**Comment by guidol70** [comment]
here cpmtools diskdefs for a 128MB .cf or .img file
(for .cf a 1K/2sec offset is supported)
Drives a named
for .cf: rc2040cfa - rc2040cfp
for .img: rc2040imga - rc2040imgp
[RC2040cf_diskdefs.txt](https://github.com/ExtremeElectronics/RC2040/files/8495682/RC2040cf_diskdefs.txt)
[RC2040img_diskdefs.txt](https://github.com/ExtremeElectronics/RC2040/files/8495683/RC2040img_diskdefs.txt)

**Comment by ExtremeElectronics** [comment]
Thanks :) 
Tried both with CPMtools GUI (http://star.gmobb.jp/koji/cgi/wiki.cgi?page=CpmtoolsGUI) , neither work past the first drive. 
Ill have a play with the "proper" CLI ones later. 

Its so frustrating CPM file manager is so close, but just not usable for me. If only you could provide the disk defs I think it would work. 

I might try creating an image from the program itself and see if its different from the 128k images we are using.

**Comment by ExtremeElectronics** [comment]
Same issue with images created by CPM manager itself. After transferring a few files it stops with no error on drag drop or  Crashes with error on File import.

**Comment by guidol70** [comment]
> Same issue with images created by CPM manager itself. After transferring a few files it stops with no error on drag drop or Crashes with error on File import.

I transfered the complete Wordstar and Turbo Pacal in a 128MB image with no problems

But when the program does create a empty image it uses 
128.000.000 byte.
In dont know how it works on drive p: because P. is only 2MB in size and maybe the program think its also 8MB like A: - O

![DiskManager_Pascal](https://user-images.githubusercontent.com/5121124/163572721-a860f624-f555-40eb-a7ad-2bca87c53ade.jpg)
[CPM128MB_non_header.zip](https://github.com/ExtremeElectronics/RC2040/files/8495970/CPM128MB_non_header.zip)
:

**Comment by ExtremeElectronics** [comment]
I wonder if its a win10 thing. Ive tried with no AV and as Administrator. 

How did you move the images, cut & paste 
This is what I get. Copied the bas files, then stopped, Only give this error when using import, rather than cut/paste. 

I might try it on my laptop (win11) and a win7 machine to prove its not something with my machine.

![Screenshot 2022-04-15 141148](https://user-images.githubusercontent.com/102665314/163574772-772423f4-f0bb-4c28-a81a-a4b3e5dd0472.jpg)
?

**Comment by guidol70** [comment]
> I wonder if its a win10 thing. Ive tried with no AV and as Administrator.

I do use Win10-Prof-64Bit as normal User (also not started as Admin).
Could drag&drop and Ctrl-C/Ctrl-V

I open the image, import/drag something in & delete something and then Save the image.

Did you try the same on the image I did attach in the message above?
How did you create CPMFileManager.img

In the attached Image I had files like you imported as a Backup of MBASIC43 on K:
![MBASIC43_BACKUP](https://user-images.githubusercontent.com/5121124/163583993-2d751622-79f1-46af-a4da-d828dbd9651d.jpg)

**Comment by ExtremeElectronics** [comment]
Looks like its something to do with my source files having the readonly flag
Remove that from the directory downwards in my CPM files store and its working (mostly) 
![Screenshot 2022-04-15 152810](https://user-images.githubusercontent.com/102665314/163585475-1b5340a7-cb72-417f-855d-9e7bfa14c08e.jpg)

**Comment by ExtremeElectronics** [comment]
Added details into SD card directory, File formats.md and the README May add into my own blog too, but done in Git Hub terms
